

%Extract the data generated by the 'to workspace' block
% Using Timeseries
time             = out.u.Time; 
input             = out.u.Data(:,1); 
output         = out.y.Data(:,1);


Fs = 100;                           % Sampling Frequency
Fn = Fs/2;                          % Nyquist Frequency
L = numel(time)-1;
FTinp = fft(input)/L;
FTout = fft(output)/L;
TF = FTout ./ FTinp;                % Transfer Function
Fv = linspace(0, 1, fix(L/2)+1)*Fn; % Frequency Vector
Iv = 1:numel(Fv);                   % Index Vector
figure
subplot(2,1,1)
plot(Fv, 20*log10(abs(TF(Iv))))
title('Amplitude')
ylabel('dB')
subplot(2,1,2)
plot(Fv, angle(TF(Iv))*180/pi)
title('Phase')
ylabel('°')

figure
numerator = 1;
denominator = [1,1/5,10];
sys = tf(numerator,denominator);
w=0:0.1:50;
bode(sys,w)