clear 
clc
close all


%define model parameters 
g=10;
m=1;
c=0.5;
L=1;


%Define Timing
tStepMax    = 0.05;
tFinal      = 45;   



%Initial conditions
theta0      = 0*pi/180;
thetadot0   = 0;


%Create input called simY
t_in = linspace(0, tFinal, 100)';
T_in = zeros(size(t_in));

for k=1:length(t_in)
    if(t_in(k)<10)
        T_in(k) = t_in(k);
    else
        T_in(k) = sin(t_in(k));
    end
end

% figure 
% plot(t_in, T_in)

simY = [t_in T_in];


%Open the Simulink model
open('Models.slx');
%run sim
sim('Models.slx');




%Extract the data generated by the 'out1'  Simulink Model
% thetaSignal = ans.yout.getElement('x');
% theta       = thetaSignal.Values.Data(:,1);
% thetadot    = thetaSignal.Values.Data(:,2);
% t           = thetaSignal.Values.Time;


%Extract the data generated by the 'to workspace' block
% Using Timeseries
t             = ans.simX.Time; 
theta         = ans.simX.Data(:,1);
thetadot      = ans.simX.Data(:,2);



%Extract the data generated by the 'to workspace' block
% Using Structwithtime format
% t             = ans.simX.time;
% theta         = ans.simX.signals.values(:,1);
% thetadot      = ans.simX.signals.values(:,2);





%Find max
[thetaMax, imax] = max(theta);
tMax = t(imax);

figure 
subplot(2,1,1)
hold on
plot(t,theta)
plot(tMax, thetaMax, 'rx', 'LineWidth', 2, 'MarkerSize', 14)
xlabel('t (seconds)');
ylabel('\theta (rad)');
grid on
title('Data generated by the system');
legend('\theta','max(\theta)');


subplot(2,1,2)
plot(t, thetadot)
xlabel('t (seconds)');
ylabel('d\theta/dt (rad/s');
grid on